#!/usr/bin/env bash

FILE=$1
VERSION_NUMBER=$(grep 'VERSION=v' $FILE | sed "s/VERSION=v//g")
ICREMENTED_VERSION_NUMBER=$((VERSION_NUMBER+1))
sed -i "s/VERSION=v$VERSION_NUMBER/VERSION=v$ICREMENTED_VERSION_NUMBER/g" $1

echo "v$ICREMENTED_VERSION_NUMBER"