name: reef-explorer Deploy

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'What services would you like to build e.g. "graphql crawler"'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SERVER_KNOWN_HOSTS }}
      - run: echo "DOCKER_HOST=${{ secrets.SERVER_DOCKER_HOST }}" >> $GITHUB_ENV
      - if: github.ref != 'refs/heads/develop'
        run: ./resources/increment_version.sh .env
      - run: make net=testnet env=prod cmd=pull services=${{ github.event.inputs.services }} execute
      - run: make net=testnet env=prod services=${{ github.event.inputs.services }} up
