name: reef-explorer CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: "**"

  workflow_dispatch:

jobs:
  unit-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspaces run test
      - run: yarn workspaces run lint
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make net=dev env=prod up
    - run: docker-compose --env-file .env -f resources/docker-compose-integration.yml run --rm hardhat_examples
